line-length = 110
target-version = "py310"

[lint]
ignore = ["PLR0913", "PLR2004"]
select = ["F", "E", "W", "C90", "I", "N", "UP", "ANN", "PL", "TC"]

[lint.per-file-ignores]
"**/__init__.py" = ["F403", "F401"]
"test.py" = ["ALL"]

[lint.flake8-type-checking]
quote-annotations = true

[lint.isort]
required-imports = ["from __future__ import annotations"]
